os:
  - linux
services:
  - docker
language: java
node_js:
  - "6.9.4"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - java -version
script:
  - ./gradlew clean
  - ./gradlew build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
