management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: Robo-Insta
    jackson:
        serialization.write_dates_as_timestamps: false
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
    port: 8080

amazon:
    dynamodb:
        endpoint: http://localhost:8000/
    aws:
        accesskey: key
        secretkey: key2

application:
debug: true

logging:
  level:
    org.springframework.security: DEBUG

roboinsta:
    credentials:
        username: test
        password: test
